# Generated by Django 5.0.7 on 2024-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_user_alter_staffinfo_age_alter_staffinfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
