# Generated by Django 5.0.7 on 2024-07-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_user_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffinfo',
            options={'permissions': (('can_view_staff', 'view all staff we queried'), ('can_edit_staff', 'edit all staffthaat match with id'), ('can_delete_staff', 'delete staff who match with id'), ('can_create_staff', 'create any staff he or she wants'))},
        ),
    ]
