# Generated by Django 5.0.7 on 2024-07-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staffinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffinfo',
            options={},
        ),
    ]
